### Creating Arrays Using the `array` Module in Python

The `array` module in Python provides a way to create and manipulate arrays with efficient storage of data elements. To create an array using the `array` module, follow these general steps:

1. **Import the `array` Module**:
   - Begin by importing the `array` module in your Python script : 
     ```python
     import array
     ```

2. **Specify the Array Type and Initialize**:
   - Use the `array.array(typecode, iterable)` constructor to create an array:
     - `typecode`: Specifies the type of elements in the array (e.g., 'i' for integers, 'f' for floats).
     - `iterable`: Provides initial data to populate the array (optional).
     - Example:
       ```python
       import array

       # Create an array of integers
       int_array = array.array('i', [1, 2, 3, 4, 5])
       ```

3. **Access and Manipulate the Array**:
   - Once the array is created, you can access and manipulate its elements using index notation (`array[index]`) and various array methods provided by the `array` module.
     - Example:
       ```python
       import array

       # Create an array of characters
       char_array = array.array('u', ['a', 'b', 'c', 'd'])

       # Access elements
       print(char_array[0])  # Output: 'a'

       # Modify elements
       char_array[1] = 'x'
       print(char_array)  # Output: array('u', ['a', 'x', 'c', 'd'])
       ```

4. **Supported Type Codes for Arrays in Python**:

| Type Code | C Type              | Python Type        | Minimum Size (bytes) |
|-----------|---------------------|--------------------|----------------------|
| `'b'`     | signed char         | `int`              | 1                    |
| `'B'`     | unsigned char       | `int`              | 1                    |
| `'h'`     | signed short        | `int`              | 2                    |
| `'H'`     | unsigned short      | `int`              | 2                    |
| `'i'`     | signed int          | `int`              | 2                    |
| `'I'`     | unsigned int        | `int` or `long`    | 2                    |
| `'l'`     | signed long         | `int`              | 4                    |
| `'L'`     | unsigned long       | `long`             | 4                    |
| `'q'`     | signed long long    | `long`             | 8                    |
| `'Q'`     | unsigned long long  | `long`             | 8                    |
| `'f'`     | float               | `float`            | 4                    |
| `'d'`     | double              | `float`            | 8                    |

These type codes specify the data type of elements that can be stored in arrays created using the `array` module in Python. Each type code corresponds to a specific C data type and Python data type, along with the minimum size (in bytes) required to store each element in memory.

For example, to create an array of integers (`'i'` type code) or floats (`'f'` type code), you can use the `array.array(typecode)` constructor and populate the array with respective data elements.

***Note: The actual size of Python integers (`int`) and floats (`float`) may vary based on the platform and Python interpreter used.***



#### One-Dimensional Array:

In [5]:
# Creation of array using array module
from array import *

arr1 = array('i', [10, 20, 30, 40, 50])

# Printing array
print("Array arr1 is :")
print(arr1)
print("--------------------")
# Accessing array elements
print("Elements of array are:")
for i in arr1:
    print(i)
print("--------------------")
# Accessing array elements using index
print("First element in array arr1 is :")
print(arr1[0])
print("--------------------")
# Printing typecode of array
print("Typecode of array arr1 is :")
print(arr1.typecode)
print("--------------------")
# Printing type of array
print("Type of array arr1 is :")
print(type(arr1))
print("--------------------")

# Notice that type of array is <class 'array.array'> and typecode is 'i' which represents signed integer.



Array arr1 is :
array('i', [10, 20, 30, 40, 50])
--------------------
Elements of array are:
10
20
30
40
50
--------------------
First element in array arr1 is :
10
--------------------
Typecode of array arr1 is :
i
--------------------
Type of array arr1 is :
<class 'array.array'>
--------------------


In [34]:
# Operations on array

# 1. Insertion

# Inserting element at end of array
print("Inserting element at end of array")
print("Array before insertion:")
print(arr1)
arr1.insert(5, 60) # Inserting 60 at index 5 i.e. at the end of array
print("Array after insertion:")
print(arr1)
print("--------------------")

# Inserting element at beginning of array
print("Inserting element at beginning of array")
print("Array before insertion:")
print(arr1)
arr1.insert(0, 5) # Inserting 5 at index 0 i.e. at the beginning of array
print("Array after insertion:")
print(arr1)
print("--------------------")

# Inserting element at specific index
print("Inserting element at specific index")
print("Array before insertion:")
print(arr1)
arr1.insert(3, 35) # Inserting 35 at index 3
print("Array after insertion:")
print(arr1)
print("--------------------")

# Time complexity of insertion operation at beginning of array is O(n) ; at end of array is O(1) and at specific index is O(n)


Inserting element at end of array
Array before insertion:
array('i', [5, 10, 20, 30, 40, 50, 60])
Array after insertion:
array('i', [5, 10, 20, 30, 40, 60, 50, 60])
--------------------
Inserting element at beginning of array
Array before insertion:
array('i', [5, 10, 20, 30, 40, 60, 50, 60])
Array after insertion:
array('i', [5, 5, 10, 20, 30, 40, 60, 50, 60])
--------------------
Inserting element at specific index
Array before insertion:
array('i', [5, 5, 10, 20, 30, 40, 60, 50, 60])
Array after insertion:
array('i', [5, 5, 10, 35, 20, 30, 40, 60, 50, 60])
--------------------


In [8]:
# 2. Traversal

# Traversing array using for loop
# Notice that we are using arr1.index(i) to get index of element i in array arr1
# You can use for loop without index as well
print("Elements of array are (using for loop):")
for i in arr1:
    print("arr1[", arr1.index(i), "] = ", i)
print("--------------------")

# Generally, we use for loop to traverse array as it is more readable and easy to use
# Traversing array using while loop
print("Elements of array are (using while loop):")
i = 0
while i < len(arr1):
    print("arr1[", i, "] = ", arr1[i])
    i += 1
print("--------------------")

# Time complexity of traversal operation is O(n)


Elements of array are (using for loop):
arr1[ 0 ] =  5
arr1[ 1 ] =  10
arr1[ 2 ] =  20
arr1[ 3 ] =  35
arr1[ 4 ] =  30
arr1[ 5 ] =  40
arr1[ 6 ] =  50
arr1[ 7 ] =  60
--------------------
Elements of array are (using while loop):
arr1[ 0 ] =  5
arr1[ 1 ] =  10
arr1[ 2 ] =  20
arr1[ 3 ] =  35
arr1[ 4 ] =  30
arr1[ 5 ] =  40
arr1[ 6 ] =  50
arr1[ 7 ] =  60
--------------------


In [17]:
# 3. Accessing , Searching

# Accessing element at specific index
print("Element at index 3 is :")
print(arr1[3])
# Accessing element not present in array
try:
    print("Element at index 10 is :")
    print(arr1[10])
except Exception as e:
    print("Index 10 is out of bounds for array arr1")
print("--------------------")

# Searching element in array
element = 35
print("Element", element, "is found at index", arr1.index(element))
# Searching element not present in array
element = 100
try:
    print("Element", element, "is found at index", arr1.index(element))
except Exception as e:
    print("Element", element, "is not found in array arr1")
print("--------------------")

# Time complexity of accessing operation is O(1) for accessing element at specific index and O(n) for searching element in array

Element at index 3 is :
35
Element at index 10 is :
Index 10 is out of bounds for array arr1
--------------------
Element 35 is found at index 3
Element 100 is not found in array arr1
--------------------


In [18]:
# 4. Deletion

# Deleting element at specific index
print("Array before deletion:")
print(arr1)
arr1.remove(35) # Deleting element 35
print("Array after deletion:")
print(arr1)
print("--------------------")

# Deleting element that is not present in array
print("Array before deletion:")
print(arr1)
try:
    arr1.remove(100) # Deleting element 100
    print("Array after deletion:")
    print(arr1)
except Exception as e:
    print("Element 100 is not found in array arr1")
print("--------------------")

# Time complexity of deletion operation is O(n) for deleting element at specific index and O(1) for deleting element at end of array


Array before deletion:
array('i', [5, 10, 20, 35, 30, 40, 50, 60])
Array after deletion:
array('i', [5, 10, 20, 30, 40, 50, 60])
--------------------
Array before deletion:
array('i', [5, 10, 20, 30, 40, 50, 60])
Element 100 is not found in array arr1
--------------------


### Creating Arrays and 2D Arrays Using NumPy in Python

NumPy is a powerful library for numerical computations in Python, including efficient handling of arrays and matrices. Here's how you can create arrays and 2D arrays (matrices) using NumPy:

1. **Import the `numpy` Module**:
   - Begin by importing the `numpy` module in your Python script or interactive session:
     ```python
     import numpy as np
     ```

2. **Creating 1D Arrays**:
   - Use `np.array(iterable)` to create a 1D array from an iterable (e.g., list, tuple).
     - Example:
       ```python
       import numpy as np

       # Create a 1D array from a list
       arr = np.array([1, 2, 3, 4, 5])
       ```

3. **Creating 2D Arrays (Matrices)**:
   - Use `np.array(list_of_lists)` to create a 2D array (matrix) from a list of lists.
     - Example:
       ```python
       import numpy as np

       # Create a 2D array (matrix) from a list of lists
       matrix = np.array([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])
       ```

4. **Specifying Data Types**:
   - You can specify the data type of elements using the `dtype` parameter in `np.array()`.
     - Example:
       ```python
       import numpy as np

       # Create a 1D array of floats
       arr_float = np.array([1.1, 2.2, 3.3], dtype=np.float64)

       # Create a 2D array (matrix) of integers
       matrix_int = np.array([[1, 2],
                              [3, 4]], dtype=np.int32)
       ```

5. **Special Array Initialization**:
   - NumPy provides functions like `np.zeros()`, `np.ones()`, `np.arange()`, etc., for creating arrays with specific initial values.
     - Example:
       ```python
       import numpy as np

       # Create a 1D array of zeros
       zeros_arr = np.zeros(5)

       # Create a 2D array (matrix) of ones
       ones_matrix = np.ones((3, 4))

       # Create a 1D array of evenly spaced values
       range_arr = np.arange(1, 10, 2)  # Output: array([1, 3, 5, 7, 9])
       ```

6. **Array Attributes and Methods**:
   - NumPy arrays have attributes like `shape`, `dtype`, and methods for array manipulation, arithmetic operations, slicing, indexing, and more.
     - Example:
       ```python
       import numpy as np

       # Create a 2D array (matrix)
       matrix = np.array([[1, 2, 3],
                          [4, 5, 6]])

       # Get array shape and data type
       print(matrix.shape)  # Output: (2, 3)
       print(matrix.dtype)  # Output: int64

       # Perform array operations
       matrix_sum = matrix.sum()        # Sum of all elements
       row_sum = matrix.sum(axis=1)     # Sum along rows
       col_mean = matrix.mean(axis=0)   # Mean along columns
       ```



#### Two-Dimensional Array:

In [20]:
# Creation of 2D array using numpy module 

import numpy as np

twod_array = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9]])
# Printing 2D array
print("2D Array is:")
print(twod_array)
print("--------------------")


# Time complexity of creation operation is O(n^2)


2D Array is:
[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]
--------------------


In [33]:
# Operations on 2D array

# 1. Insertion
twod_array = np.array([[11, 15, 0, 6], [10, 24, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9]])

# Breakdown of np.insert() function
"""
np.insert(arr, index, element, axis) where :
arr is the array in which element is to be inserted
index is the index at which element is to be inserted
element is the element to be inserted
axis is the axis along which element is to be inserted
"""

# Important points to note while inserting row or column in 2D array :
"""
Inserting row at end of 2D array : axis = 0
Inserting column in 2D array : axis = 1
After inserting row or column, the shape of 2D array changes
"""


# Inserting row at end of 2D array
print("Inserting row at end of 2D array")
print("2D Array before insertion:")
print(twod_array)
row = np.array([10, 15, 20, 25])
twod_array = np.insert(twod_array, 4, row, axis=0) 
print("2D Array after insertion:")
print(twod_array)
print("--------------------")

# Inserting column in 2D array
print("Inserting column in 2D array")
print("2D Array before insertion:")
print(twod_array)
column = np.array([7, 12, 17, 22, 27])
twod_array = np.insert(twod_array, 4, column, axis=1)
print("2D Array after insertion:")
print(twod_array)
print("--------------------")

# Time complexity of insertion operation at beginning of 2D array is O(n^2) ; at end of 2D array is O(n^2) and at specific index is O(n^2)


Inserting row at end of 2D array
2D Array before insertion:
[[11 15  0  6]
 [10 24 11  5]
 [12 17 12  8]
 [15 18 14  9]]
2D Array after insertion:
[[11 15  0  6]
 [10 24 11  5]
 [12 17 12  8]
 [15 18 14  9]
 [10 15 20 25]]
--------------------
Inserting column in 2D array
2D Array before insertion:
[[11 15  0  6]
 [10 24 11  5]
 [12 17 12  8]
 [15 18 14  9]
 [10 15 20 25]]
2D Array after insertion:
[[11 15  0  6  7]
 [10 24 11  5 12]
 [12 17 12  8 17]
 [15 18 14  9 22]
 [10 15 20 25 27]]
--------------------


In [38]:
# 2. Traversal

twod_array = np.array([[1, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9]])
# Traversing 2D array using for loop
# Notice that we are using twod_array.shape[0] and twod_array.shape[1] to get number of rows and columns in 2D array twod_array
# You can use for loop without shape as well
print("Elements of 2D array are:")
for i in range(twod_array.shape[0]):
    for j in range(twod_array.shape[1]):
        print("twod_array[", i, "][", j, "] = ", twod_array[i][j])
print("--------------------")

# To use for loop without shape, you can use twod_array[i][j] to access element at ith row and jth column

code = """
print("Elements of 2D array are:")
for i in range(len(twod_array)):
    for j in range(len(twod_array[i])):
        print("twod_array[", i, "][", j, "] = ", twod_array[i][j])
print("--------------------")
"""

# Time complexity of traversal operation is O(n^2)


Elements of 2D array are:
twod_array[ 0 ][ 0 ] =  1
twod_array[ 0 ][ 1 ] =  15
twod_array[ 0 ][ 2 ] =  10
twod_array[ 0 ][ 3 ] =  6
twod_array[ 1 ][ 0 ] =  10
twod_array[ 1 ][ 1 ] =  14
twod_array[ 1 ][ 2 ] =  11
twod_array[ 1 ][ 3 ] =  5
twod_array[ 2 ][ 0 ] =  12
twod_array[ 2 ][ 1 ] =  17
twod_array[ 2 ][ 2 ] =  12
twod_array[ 2 ][ 3 ] =  8
twod_array[ 3 ][ 0 ] =  15
twod_array[ 3 ][ 1 ] =  18
twod_array[ 3 ][ 2 ] =  14
twod_array[ 3 ][ 3 ] =  9
--------------------


In [42]:
# 3. Accessing , Searching

# Accessing element at specific index
print("Element at index 2, 3 is :")
print(twod_array[2][3])
# Accessing element not present in 2D array
try:
    print("Element at index 10, 10 is :")
    print(twod_array[10][10])
except Exception as e:
    print("Index 10, 10 is out of bounds for 2D array twod_array")
print("--------------------")

# Searching element in 2D array
element = 17
for i in range(twod_array.shape[0]):
    for j in range(twod_array.shape[1]):
        if twod_array[i][j] == element:
            print("Element", element, "is found at index", i, j)
            break

# Searching element not present in 2D array
element = 100
for i in range(twod_array.shape[0]):
    for j in range(twod_array.shape[1]):
        if twod_array[i][j] == element:
            print("Element", element, "is found at index", i, j)
            break
        else:
            print("Element", element, "is not found in 2D array twod_array")
            break
print("--------------------")
# Note `Element 100 is not found in 2D array twod_array` is printed multiple times because we are using break statement in else block

# Time complexity of accessing operation is O(1) for accessing element at specific index and O(n^2) for searching element in 2D array

Element at index 2, 3 is :
8
Element at index 10, 10 is :
Index 10, 10 is out of bounds for 2D array twod_array
--------------------
Element 17 is found at index 2 1
Element 100 is not found in 2D array twod_array
Element 100 is not found in 2D array twod_array
Element 100 is not found in 2D array twod_array
Element 100 is not found in 2D array twod_array
--------------------


In [43]:
# 4. Deletion

twod_array = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 7, 2, 8], [15, 18, 14, 9]])
# Deleting row at specific index

# Breakdown of np.delete() function
"""
np.delete(arr, index, axis) where :
arr is the array from which element is to be deleted
index is the index at which element is to be deleted
axis is the axis along which element is to be deleted
"""

print("2D Array before deletion:")
print(twod_array)
twod_array = np.delete(twod_array, 2, axis=0) # Deleting row at index 2
print("2D Array after deletion:")
print(twod_array)
print("--------------------")

# Deleting column at specific index
print("2D Array before deletion:")
print(twod_array)
twod_array = np.delete(twod_array, 2, axis=1) # Deleting column at index 2
print("2D Array after deletion:")
print(twod_array)
print("--------------------")

2D Array before deletion:
[[11 15 10  6]
 [10 14 11  5]
 [12  7  2  8]
 [15 18 14  9]]
2D Array after deletion:
[[11 15 10  6]
 [10 14 11  5]
 [15 18 14  9]]
--------------------
2D Array before deletion:
[[11 15 10  6]
 [10 14 11  5]
 [15 18 14  9]]
2D Array after deletion:
[[11 15  6]
 [10 14  5]
 [15 18  9]]
--------------------
